# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from protos.wallet import wallet_pb2 as protos_dot_wallet_dot_wallet__pb2

GRPC_GENERATED_VERSION = "1.65.1"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.66.0"
SCHEDULED_RELEASE_DATE = "August 6, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in protos/wallet/wallet_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class WalletServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_accounts = channel.unary_stream(
            "/wallet.WalletService/get_accounts",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=protos_dot_wallet_dot_wallet__pb2.AccountResponse.FromString,
            _registered_method=True,
        )
        self.get_operations = channel.unary_stream(
            "/wallet.WalletService/get_operations",
            request_serializer=protos_dot_wallet_dot_wallet__pb2.GetOperationsRequest.SerializeToString,
            response_deserializer=protos_dot_wallet_dot_wallet__pb2.OperationResponse.FromString,
            _registered_method=True,
        )
        self.get_tags = channel.unary_stream(
            "/wallet.WalletService/get_tags",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=protos_dot_wallet_dot_wallet__pb2.TagResponse.FromString,
            _registered_method=True,
        )
        self.create_account = channel.unary_unary(
            "/wallet.WalletService/create_account",
            request_serializer=protos_dot_wallet_dot_wallet__pb2.CreateAccountRequest.SerializeToString,
            response_deserializer=protos_dot_wallet_dot_wallet__pb2.AccountResponse.FromString,
            _registered_method=True,
        )
        self.rename_account = channel.unary_unary(
            "/wallet.WalletService/rename_account",
            request_serializer=protos_dot_wallet_dot_wallet__pb2.RenameAccountRequest.SerializeToString,
            response_deserializer=protos_dot_wallet_dot_wallet__pb2.AccountResponse.FromString,
            _registered_method=True,
        )
        self.remove_account = channel.unary_unary(
            "/wallet.WalletService/remove_account",
            request_serializer=protos_dot_wallet_dot_wallet__pb2.RemoveAccountRequest.SerializeToString,
            response_deserializer=protos_dot_wallet_dot_wallet__pb2.AccountResponse.FromString,
            _registered_method=True,
        )
        self.add_operation = channel.unary_unary(
            "/wallet.WalletService/add_operation",
            request_serializer=protos_dot_wallet_dot_wallet__pb2.AddOperationRequest.SerializeToString,
            response_deserializer=protos_dot_wallet_dot_wallet__pb2.OperationResponse.FromString,
            _registered_method=True,
        )
        self.remove_operation = channel.unary_unary(
            "/wallet.WalletService/remove_operation",
            request_serializer=protos_dot_wallet_dot_wallet__pb2.RemoveOperationRequest.SerializeToString,
            response_deserializer=protos_dot_wallet_dot_wallet__pb2.OperationResponse.FromString,
            _registered_method=True,
        )


class WalletServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_accounts(self, request, context):
        """Queries"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def get_operations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def get_tags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def create_account(self, request, context):
        """Account commands"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def rename_account(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def remove_account(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def add_operation(self, request, context):
        """Operation commands"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def remove_operation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "get_accounts": grpc.unary_stream_rpc_method_handler(
            servicer.get_accounts,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=protos_dot_wallet_dot_wallet__pb2.AccountResponse.SerializeToString,
        ),
        "get_operations": grpc.unary_stream_rpc_method_handler(
            servicer.get_operations,
            request_deserializer=protos_dot_wallet_dot_wallet__pb2.GetOperationsRequest.FromString,
            response_serializer=protos_dot_wallet_dot_wallet__pb2.OperationResponse.SerializeToString,
        ),
        "get_tags": grpc.unary_stream_rpc_method_handler(
            servicer.get_tags,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=protos_dot_wallet_dot_wallet__pb2.TagResponse.SerializeToString,
        ),
        "create_account": grpc.unary_unary_rpc_method_handler(
            servicer.create_account,
            request_deserializer=protos_dot_wallet_dot_wallet__pb2.CreateAccountRequest.FromString,
            response_serializer=protos_dot_wallet_dot_wallet__pb2.AccountResponse.SerializeToString,
        ),
        "rename_account": grpc.unary_unary_rpc_method_handler(
            servicer.rename_account,
            request_deserializer=protos_dot_wallet_dot_wallet__pb2.RenameAccountRequest.FromString,
            response_serializer=protos_dot_wallet_dot_wallet__pb2.AccountResponse.SerializeToString,
        ),
        "remove_account": grpc.unary_unary_rpc_method_handler(
            servicer.remove_account,
            request_deserializer=protos_dot_wallet_dot_wallet__pb2.RemoveAccountRequest.FromString,
            response_serializer=protos_dot_wallet_dot_wallet__pb2.AccountResponse.SerializeToString,
        ),
        "add_operation": grpc.unary_unary_rpc_method_handler(
            servicer.add_operation,
            request_deserializer=protos_dot_wallet_dot_wallet__pb2.AddOperationRequest.FromString,
            response_serializer=protos_dot_wallet_dot_wallet__pb2.OperationResponse.SerializeToString,
        ),
        "remove_operation": grpc.unary_unary_rpc_method_handler(
            servicer.remove_operation,
            request_deserializer=protos_dot_wallet_dot_wallet__pb2.RemoveOperationRequest.FromString,
            response_serializer=protos_dot_wallet_dot_wallet__pb2.OperationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "wallet.WalletService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("wallet.WalletService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class WalletService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_accounts(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/wallet.WalletService/get_accounts",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            protos_dot_wallet_dot_wallet__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def get_operations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/wallet.WalletService/get_operations",
            protos_dot_wallet_dot_wallet__pb2.GetOperationsRequest.SerializeToString,
            protos_dot_wallet_dot_wallet__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def get_tags(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/wallet.WalletService/get_tags",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            protos_dot_wallet_dot_wallet__pb2.TagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def create_account(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.WalletService/create_account",
            protos_dot_wallet_dot_wallet__pb2.CreateAccountRequest.SerializeToString,
            protos_dot_wallet_dot_wallet__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def rename_account(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.WalletService/rename_account",
            protos_dot_wallet_dot_wallet__pb2.RenameAccountRequest.SerializeToString,
            protos_dot_wallet_dot_wallet__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def remove_account(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.WalletService/remove_account",
            protos_dot_wallet_dot_wallet__pb2.RemoveAccountRequest.SerializeToString,
            protos_dot_wallet_dot_wallet__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def add_operation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.WalletService/add_operation",
            protos_dot_wallet_dot_wallet__pb2.AddOperationRequest.SerializeToString,
            protos_dot_wallet_dot_wallet__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def remove_operation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.WalletService/remove_operation",
            protos_dot_wallet_dot_wallet__pb2.RemoveOperationRequest.SerializeToString,
            protos_dot_wallet_dot_wallet__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class ReportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_latest_operations = channel.unary_stream(
            "/wallet.ReportService/get_latest_operations",
            request_serializer=protos_dot_wallet_dot_wallet__pb2.GetLatestOperationRequest.SerializeToString,
            response_deserializer=protos_dot_wallet_dot_wallet__pb2.OperationResponse.FromString,
            _registered_method=True,
        )


class ReportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_latest_operations(self, request, context):
        """Queries"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ReportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "get_latest_operations": grpc.unary_stream_rpc_method_handler(
            servicer.get_latest_operations,
            request_deserializer=protos_dot_wallet_dot_wallet__pb2.GetLatestOperationRequest.FromString,
            response_serializer=protos_dot_wallet_dot_wallet__pb2.OperationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "wallet.ReportService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("wallet.ReportService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ReportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_latest_operations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/wallet.ReportService/get_latest_operations",
            protos_dot_wallet_dot_wallet__pb2.GetLatestOperationRequest.SerializeToString,
            protos_dot_wallet_dot_wallet__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
