name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install --user pdm tox

      - name: Check with Ruff formatter.
        env:
          TOXENV: format
        run: "python -m tox"

  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install --user pdm tox

      - name: Check with Ruff linter
        env:
          TOXENV: ruff
        run: "python -m tox"
